### PR TITLE
check forms button working

### PR DESCRIPTION
**Pull request by JaneCameSixth**

### CODE REVIEW

**Comment by fgbernardez** [comment]
Hala. Seryoso ning Commit Summary na "dsadasd" ? 😩

Respectfully,



*Fernand G. Bernardez*
Instructor I
University of the Philippines Cebu
Lahug, Cebu City, Philippines
Mobile No. +639
95 1008110

**Comment by JaneCameSixth** [comment]
ngek mangita daay commit nga title oh noes... abi kog sa pull request ug
merge ra makita, sorry sirrr

**Comment by fgbernardez** [comment]
Makita nako ang tanan. 😁😂

Respectfully,

*Fernand G. Bernardez*
Instructor I
University of the Philippines Cebu
Lahug, Cebu City, Philippines
Mobile No. +639
95 1008110

**Comment by JaneCameSixth** [comment]
HOMAYY HAHAHAHAH gege sir next oks na ang commits sakspan nuon ko dza

**Pull request merged**
